In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('post_dataframe.csv', index_col='Unnamed: 0')

In [3]:
df_d = df['Диагноз'].values
for i in range(len(df_d)):
    if df_d[i] == 2:
        df_d[i] = 1
df['Диагноз'] = df_d[:]

In [4]:
df_train = df[:]
df_test = df[:]

In [5]:
TRAIN_TEST_RATIO = 0.65
train_number = round(df.shape[0] * TRAIN_TEST_RATIO)
print(train_number)

# train
X_train = df_train.drop(['Диагноз'], axis=1).iloc[:train_number]
y_train = df_train['Диагноз'].iloc[:train_number].values

# test
X_test = df_test.drop(['Диагноз'], axis=1).iloc[train_number:]
y_test = df_test['Диагноз'].iloc[train_number:].values

232


In [6]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.naive_bayes import BernoulliNB

In [7]:
random_forest = RandomForestRegressor().fit(X_train, y_train)
bernoulli = BernoulliNB().fit(X_train, y_train)

/home/kaktus2/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [8]:
print("\nRandom Forest Regressor:\nTrain: {}".format(random_forest.score(X_train, y_train)))
print("Test: {}".format(random_forest.score(X_test, y_test)))


Random Forest Regressor:
Train: 0.8699292149292149
Test: 0.2675576519916144


In [9]:
print("\nNaive Baies:\nTrain: {}".format(bernoulli.score(X_train, y_train)))
print("Test: {}".format(bernoulli.score(X_test, y_test)))


Naive Baies:
Train: 0.8232758620689655
Test: 0.8


In [10]:
X_train.iloc[0].values

array([ 0, 61,  0,  0,  1,  0,  0,  0,  1,  1,  1,  0,  1,  1,  0,  1,  1,
        1,  1,  1,  0,  1,  1,  1,  0,  1,  1,  1,  1,  0,  0,  1,  0])

In [11]:
X_train.iloc[0].values.reshape(1, -1)

array([[ 0, 61,  0,  0,  1,  0,  0,  0,  1,  1,  1,  0,  1,  1,  0,  1,
         1,  1,  1,  1,  0,  1,  1,  1,  0,  1,  1,  1,  1,  0,  0,  1,
         0]])

In [12]:
for i in range(200):
    if bernoulli.predict(X_train.iloc[i].values.reshape(1, -1)) == y_train[i]:
        print("Correct predict")
    else:
        print("Incorrect predict")

Correct predict
Correct predict
Correct predict
Correct predict
Correct predict
Incorrect predict
Correct predict
Incorrect predict
Correct predict
Correct predict
Correct predict
Correct predict
Correct predict
Correct predict
Correct predict
Correct predict
Correct predict
Correct predict
Correct predict
Correct predict
Correct predict
Incorrect predict
Incorrect predict
Correct predict
Correct predict
Correct predict
Correct predict
Incorrect predict
Correct predict
Correct predict
Correct predict
Correct predict
Correct predict
Correct predict
Correct predict
Correct predict
Incorrect predict
Correct predict
Correct predict
Correct predict
Correct predict
Incorrect predict
Correct predict
Correct predict
Incorrect predict
Incorrect predict
Correct predict
Correct predict
Correct predict
Incorrect predict
Correct predict
Incorrect predict
Correct predict
Correct predict
Correct predict
Correct predict
Incorrect predict
Correct predict
Correct predict
Correct predict
Correct predict


In [13]:
bernoulli.predict(X_train.iloc[0].values.reshape(1, -1))

array([1])

In [14]:
import pickle
s = pickle.dumps(bernoulli)
saved_bernoulli = pickle.loads(s)
saved_bernoulli.predict(X_train.iloc[0].values.reshape(1, -1))

array([1])

## Функция выдачи результата по запросу

In [16]:
def predict_diagnosis(answers):
    saved_bernoulli = pickle.loads(s)
    diagnosis = saved_bernoulli.predict(answers.values.reshape(1, -1))
    return diagnosis

In [19]:
print(int(predict_diagnosis(X_train.iloc[2])))

1
